WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1695569348.604756 3248566 tfrt_cpu_pjrt_client.cc:349] TfrtCpuClient created.
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/scvi/_settings.py:63: UserWarning: Since v1.0.0, scvi-tools no longer uses a random seed by default. Run `scvi.settings.seed = 0` to reproduce results from previous versions.
  self.seed = seed
/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/scvi/_settings.py:70: UserWarning: Setting `dl_pin_memory_gpu_training` is deprecated in v1.0 and will be removed in v1.1. Please pass in `pin_memory` to the data loaders instead.
  self.dl_pin_memory_gpu_training = (
wandb: Currently logged in as: allepalma. Use `wandb login --relogin` to force relogin
wandb: wandb version 0.15.11 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.15.10
wandb: Run data is saved locally in /home/icb/alessandro.palma/environment/scCFM/project_dir/experiments/4_OFFICIAL_cfm_schiebinger_latent_flat_LEAVEOUT/wandb/run-20230924_173000-6v90k0mt
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run golden-violet-9
wandb: ‚≠êÔ∏è View project at https://wandb.ai/allepalma/4_OFFICIAL_cfm_schiebinger_latent_flat_LEAVEOUT
wandb: üöÄ View run at https://wandb.ai/allepalma/4_OFFICIAL_cfm_schiebinger_latent_flat_LEAVEOUT/runs/6v90k0mt
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:617: UserWarning: Checkpoint directory /lustre/groups/ml01/workspace/alessandro.palma/scCFM/experiments/4_OFFICIAL_cfm_schiebinger_latent_flat_LEAVEOUT/checkpoints exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name      | Type      | Params
----------------------------------------
0 | net       | MLP       | 9.9 K 
1 | node      | NeuralODE | 9.9 K 
2 | criterion | MSELoss   | 0     
----------------------------------------
9.9 K     Trainable params
0         Non-trainable params
9.9 K     Total params
0.039     Total estimated model params size (MB)
SLURM auto-requeueing enabled. Setting signal handlers.
/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:442: PossibleUserWarning: The dataloader, val_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 112 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Traceback (most recent call last):
  File "/home/icb/alessandro.palma/environment/scCFM/scCFM/train_hydra/utils/exceptions.py", line 11, in __call__
    return self.f(*args, **kwargs)
  File "/home/icb/alessandro.palma/environment/scCFM/scCFM/train_hydra/train_cfm.py", line 119, in main
    trainer.fit(model=model,
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 980, in _run
    results = self._run_stage()
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1021, in _run_stage
    self._run_sanity_check()
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1050, in _run_sanity_check
    val_loop.run()
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 115, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 376, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_kwargs.values())
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 294, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 393, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/icb/alessandro.palma/environment/scCFM/scCFM/models/cfm/cfm_module.py", line 245, in validation_step
    loss = self.step(batch, training=False)
  File "/home/icb/alessandro.palma/environment/scCFM/scCFM/models/cfm/cfm_module.py", line 229, in step
    t, xt, ut = self.preprocess_batch(X)
  File "/home/icb/alessandro.palma/environment/scCFM/scCFM/models/cfm/cfm_module.py", line 202, in preprocess_batch
    x1 = X[:, t_next, :]
IndexError: index 39 is out of bounds for dimension 1 with size 39
wandb: Waiting for W&B process to finish... (success).
wandb: üöÄ View run golden-violet-9 at: https://wandb.ai/allepalma/4_OFFICIAL_cfm_schiebinger_latent_flat_LEAVEOUT/runs/6v90k0mt
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: /home/icb/alessandro.palma/environment/scCFM/project_dir/experiments/4_OFFICIAL_cfm_schiebinger_latent_flat_LEAVEOUT/wandb/run-20230924_173000-6v90k0mt/logs
Exception in thread Exception in thread IntMsgThrNetStatThr:
:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()    
self.run()  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/threading.py", line 953, in run

  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 299, in check_internal_messages
    self._target(*self._args, **self._kwargs)
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 267, in check_network_status
    self._loop_check_status(
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 223, in _loop_check_status
    local_handle = request()
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 735, in deliver_network_status
    self._loop_check_status(
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 223, in _loop_check_status
    local_handle = request()
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 743, in deliver_internal_messages
    return self._deliver_internal_messages(internal_message)
      File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 472, in _deliver_internal_messages
return self._deliver_network_status(status)
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 466, in _deliver_network_status
    return self._deliver_record(record)
      File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 425, in _deliver_record
return self._deliver_record(record)
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 425, in _deliver_record
    handle = mailbox._deliver_record(record, interface=self)
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
    handle = mailbox._deliver_record(record, interface=self)
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
        interface._publish(record)interface._publish(record)

  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self._sock_client.send_record_publish(record)
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self.send_server_request(server_req)
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._send_message(msg)
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
      File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
self._sendall_with_error_handle(header + data)
  File "/home/icb/alessandro.palma/miniconda3/envs/scCFM/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError:     [Errno 32] Broken pipesent = self._sock.send(data)

BrokenPipeError: [Errno 32] Broken pipe
